review
boledovicpantheon/PA-19 pull request #3
Opened 2022-08-09 12:02 UTC by boledovicpantheon

2022-08-25 05:28 UTC, pmikus commented on .github/workflows/action.yml
> +        run: vagrant validate
Any reason why there is macos-10.15 as executor?

2022-08-25 05:31 UTC, pmikus commented on Vagrantfile
> +
If there would be 1000 VMs how would you name all of them?

2022-08-25 05:32 UTC, pmikus commented on Vagrantfile
> +  config.vm.define "#{vm1_name}" do |vm1|
I prefer to use:
`config.vm.define "ubuntu_impish....." do |vm|`

2022-08-25 05:33 UTC, pmikus commented on Vagrantfile
> +    vm1.vm.box = "#{vagrant_box_dir}/#{vm1_box_file_name}"
`flavor.vm.box = "#{vagrant_box_dir}/ubuntu......"`

2022-08-25 05:36 UTC, pmikus requested changes
Please see the comments

2022-08-25 07:52 UTC, boledovicpantheon commented on .github/workflows/action.yml
> +        run: vagrant validate
I couldn't find GitHub action with Ubuntu or any other Linux distribution as executor, that's why.

2022-08-25 08:41 UTC, boledovicpantheon commented on Vagrantfile
> +  config.vm.define "#{vm1_name}" do |vm1|
Should i do something like:
1..N
if N=1 then create focal, 
if N=2 then create jammy?

2022-08-26 11:21 UTC, pmikus commented on Vagrantfile
> +      vb.name = "jammy"
ubuntu_jammy from consistency point of view

2022-08-26 11:21 UTC, pmikus commented on Vagrantfile
> +    focal.vm.box = "#{vagrant_box_dir}/packer_ubuntu-server-22.04.box"
focal is 20.04

2022-08-26 11:23 UTC, pmikus commented on Vagrantfile
> +    ansible.inventory_path = "PA-20/inventory/"
it is always better to name it like "ansible/..." instead PA-20 which is reference to JIRA but the code or reader may not know what it is.

2022-08-26 11:23 UTC, pmikus requested changes
few comments

2022-08-30 07:09 UTC, pmikus commented on Vagrantfile
> +  config.vm.define "#{vm1_name}" do |vm1|
No, leave is universal so it can be extended.
e.g
`config.vm.define "ubuntu_impish" do |flavor|`
but later you can do 
`
Vagrant.configure("2") do |config|
    ...
    config.vm.define "ubuntu_focal" do |flavor|
        flavor.vm.box_url = "..."
        flavor.vm.box = "..."
        configure_provider(flavor, "Ubuntu_Focal")
    end
    config.vm.define "ubuntu_jammy" do |flavor|
        flavor.vm.box_url = "..."
        flavor.vm.box = "..."
        configure_provider(flavor, "Ubuntu_Jammy")
    end
end

def configure_provider (node, node_name)
  node.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--usb", "on"]
    ....
    vb.cpus = 2
    vb.gui = true
    vb.name = node_name
  end
end

`

2022-08-30 07:14 UTC, boledovicpantheon commented on Vagrantfile
> +  config.vm.define "#{vm1_name}" do |vm1|
Okay, done

2022-09-06 08:05 UTC, pmikus approved these changes

2022-09-06 08:55 UTC, merged